---
- name: Deploy app
  hosts: app
  become: true
  tasks:

    - name: Install git for app server
      ansible.builtin.apt:
        name: git
        update_cache: true
        cache_valid_time: 3600

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
