---
  plugin: yc_compute
  folders: b1g3uo7jmc1ebgnu7cup
  filters:
    status == 'RUNNING'
  auth_kind: serviceaccountfile
  service_account_file: /home/alex/.ssh/key_tf.json
  hostnames: "{{name}}"
  compose:
    ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
  groups:
    db: labels['tags'] == 'reddit-db'
    app:  labels['tags'] == 'reddit-app'
