- name: install for app srv
  hosts: all
  become: true
  tasks:

    - name: Install ruby and bundler for host
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      loop:
      - ruby-full
      - ruby-bundler
      - build-essential

