- name: install for db srv
  hosts: all
  become: true
  tasks:

    - name: install mongodb and update cache
      ansible.builtin.apt:
        name: mongodb
        update_cache: yes
        cache_valid_time: 3600

    - name: enable mongo
      systemd:
        name: mongodb
        enabled: yes
